version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER_NAME}", "-d", "${DB_NAME}", "-h", "${DB_HOST}", "-p", "${DB_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todo_app_network

  todo-app:
    container_name: todo-go-app
    build: ./
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TERM=xterm
      - DATABASE_URL=postgres://${DB_USER_NAME}:${DB_PASSWORD}@postgres-db:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}
    command: bash -c "/usr/local/bin/migrate -path ./schema -database 'postgres://${DB_USER_NAME}:${DB_PASSWORD}@postgres-db:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}' up"
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f todo-go-app" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - todo_app_network

networks:
  todo_app_network:
    driver: bridge